### PR TITLE
October Improvements 1/2

### PR DESCRIPTION
**Pull request by phschaad**
- [x] Visualize empty memlets (i.e., dependency edges) as dotted lines. Closes https://github.com/spcl/dace-vscode/issues/245.
  The example below shows both an empty memlet (top), as well as the current style of WCR edges (bottom) and how they differ in the visualization.
  image
- [x] Highlight symbols being used in tasklets. Additionally, hovering over a connector highlights the corresponding variables inside the tasklet code. The image below shows both a symbol being highlighted (red), and a connector (green). The colors are CSS customizable variables. Closes https://github.com/spcl/dace-vscode/issues/243.
  image

### CODE REVIEW

**Comment by tbennun** [comment]
Please provide a screenshot here :)

**Comment by tbennun** [comment]
I'd also use a gray color myself. However, we may have discussed using that for non-leaf memlets just to emphasize that they do not generate code.

**Comment by phschaad** [comment]
> I'd also use a gray color myself. However, we may have discussed using that for non-leaf memlets just to emphasize that they do not generate code.

I agree with this, but as you pointed out the gray is already going to be (most likely) occupied. Do you have a suggestion of what other style we could use? I agree that the color should ideally also differ.

**Comment by tbennun** [comment]
This looks good. Maybe no arrowhead would make that difference

**Comment by phschaad** [comment]
> This looks good. Maybe no arrowhead would make that difference. You need it connected, not moving.

Good idea, I'll make that change

**Comment by phschaad** [comment]
> This looks good. Maybe no arrowhead would make that difference. You need it connected, not moving. In that case, maybe the line can even stay solid..? Unsure

Done

**Review by tbennun — APPROVED** [review]
Looks good. Tasklet highlighter might be slow for long codes but that should not be the default case. We may want to consider a length cutoff where we just draw the contents.

**Comment by phschaad** [comment]
> Looks good. Tasklet highlighter might be slow for long codes but that should not be the default case. We may want to consider a length cutoff where we just draw the contents.

We should observe, a cutoff would be easy to add if necessary. The length of the tasklet code itself should not have a noticeable impact, only tasklets with dozens of in/out connectors each could potentially pose a challenge in my view.

**Pull request merged**
